application: wordsmashing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "300d 5h"

handlers:
- url: /manifest.webapp
  static_files: manifest/manifest.json
  upload: manifest/manifest.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json

- url: /manifest-noads.webapp
  static_files: manifest/manifest-noads.json
  upload: manifest/manifest-noads.json
  http_headers:
    Content-Type: application/x-web-app-manifest+json

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
- url: /transient/*
  static_dir: transient
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: transient/robots.txt
  upload: transient/robots.txt

- url: /apple-touch-icon.png
  static_files: static/img/apple-touch-icon.png
  upload: static/img/apple-touch-icon.png

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml
- url: /channel.html
  static_files: static/channel.html
  upload: static/channel.html

- url: /gameon/static/*
  static_dir: gameon/static
  http_headers:
    Vary: Accept-Encoding
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

instance_class: F2
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

pagespeed:

  url_blacklist:
  - http://www.wordsmashing.com/static/music/*
  - http://www.wordsmashing.com/sitemap
  - http://www.wordsmashing.com/manifest.webapp
  - http://www.wordsmashing.com/manifest-noads.webapp
  - https://wordsmashing.appspot.com/buy
  # enabled_rewriters:
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - MinifyCss
  # - InlineJs
  # - LeftTrimUrls

inbound_services:
- warmup

builtins:
- appstats: on

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
